11

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,23 +1,49 @@
 #!/usr/bin/env bash
-# Manages "manage_my_process"
-killer() {
-    kill "$(pgrep -f /manage_my_process)"
-    rm -f /var/run/my_process.pid &
+# Manages "manage_my_process"#!/bin/bash
+
+PID_FILE="/var/run/my_process.pid"
+MANAGE_SCRIPT="./manage_my_process"
+
+start() {
+    if [ -f "$PID_FILE" ]; then
+        echo "Error: manage_my_process is already running. PID: $(cat $PID_FILE)"
+    else
+        $MANAGE_SCRIPT &
+        echo $! > $PID_FILE
+        echo "manage_my_process started"
+    fi
 }
 
-if [[ "$1" == "start" ]]
-then
-    ./manage_my_process &
-    echo "$!" > /var/run/my_process.pid
-    echo "manage_my_process started"
-elif [[ "$1" == "stop" ]]
-then
-    killer; echo "manage_my_process stopped";
-elif [[ "$1" == "restart" ]]
-then
-    killer; ./manage_my_process &
-    echo "$!" > /var/run/my_process.pid
+stop() {
+    if [ -f "$PID_FILE" ]; then
+        kill $(cat $PID_FILE)
+        rm $PID_FILE
+        echo "manage_my_process stopped"
+    else
+        echo "Error: manage_my_process is not running."
+    fi
+}
+
+restart() {
+    stop
+    start
     echo "manage_my_process restarted"
-else
-    echo "Usage: manage_my_process {start|stop|restart}"
-fi
+}
+
+case "$1" in
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        restart
+        ;;
+    *)
+        echo "Usage: manage_my_process {start|stop|restart}"
+        exit 1
+        ;;
+esac
+
+exit 0
